Ext.ModEvents.BG3SX.SexStartSpellUsed:Subscribe(function (payload)
    _P("SexStartSpellUsed received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SexAnimationChange:Subscribe(function (payload)
    _P("SexAnimationChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneInit:Subscribe(function (payload)
    _P("SceneInit received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneCreated:Subscribe(function (payload)
    _P("SceneCreated received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.ActorInit:Subscribe(function (payload)
    _P("ActorInit received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.ActorCreated:Subscribe(function (payload)
    _P("ActorCreated received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.AnimationChange:Subscribe(function (payload)
    _P("AnimationChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SoundChange:Subscribe(function (payload)
    _P("SoundChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneSwitchPlacesBefore:Subscribe(function (payload)
    _P("SceneSwitchPlacesBefore received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneSwitchPlacesAfter:Subscribe(function (payload)
    _P("SceneSwitchPlacesAfter received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.CameraHeightChange:Subscribe(function (payload)
    _P("CameraHeightChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.ActorDressed:Subscribe(function (payload)
    _P("ActorDressed received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.GenitalChange:Subscribe(function (payload)
    _P("GenitalChange received with PayLoad: ")
    _D(payload)
end)