Ext.ModEvents.BG3SX.SexStartSpellUsed:Subscribe(function (payload)
    _P("[BG3SX][Events] SexStartSpellUsed received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SexAnimationChange:Subscribe(function (payload)
    _P("[BG3SX][Events] SexAnimationChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneInit:Subscribe(function (payload)
    _P("[BG3SX][Events] SceneInit received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneCreated:Subscribe(function (payload)
    _P("[BG3SX][Events] SceneCreated received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.ActorInit:Subscribe(function (payload)
    _P("[BG3SX][Events] ActorInit received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.ActorCreated:Subscribe(function (payload)
    _P("[BG3SX][Events] ActorCreated received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.AnimationChange:Subscribe(function (payload)
    _P("[BG3SX][Events] AnimationChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SoundChange:Subscribe(function (payload)
    _P("[BG3SX][Events] SoundChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneMove:Subscribe(function (payload)
    _P("[BG3SX][Events] SceneMove received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneSwitchPlacesBefore:Subscribe(function (payload)
    _P("[BG3SX][Events] SceneSwitchPlacesBefore received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.SceneSwitchPlacesAfter:Subscribe(function (payload)
    _P("[BG3SX][Events] SceneSwitchPlacesAfter received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.CameraHeightChange:Subscribe(function (payload)
    _P("[BG3SX][Events] CameraHeightChange received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.ActorDressed:Subscribe(function (payload)
    _P("[BG3SX][Events] ActorDressed received with PayLoad: ")
    _D(payload)
end)
Ext.ModEvents.BG3SX.GenitalChange:Subscribe(function (payload)
    _P("[BG3SX][Events] GenitalChange received with PayLoad: ")
    _D(payload)
end)
-- Ext.ModEvents.BG3SX.NPCStrip:Subscribe(function (payload)
--     _P("[BG3SX][Events] NPCStrip received with PayLoad: ")
--     _D(payload)
-- end)
-- Ext.ModEvents.BG3SX.NPCDress:Subscribe(function (payload)
--     _P("[BG3SX][Events] NPCDress received with PayLoad: ")
--     _D(payload)
-- end)

-- TODO: Test if this works as well to just listen to ANY event of a mod
-- for _,e in pairs(Ext.ModEvents.BG3SX) do
--     e:Subscribe(function (payload)
--         _P("Recieved " .. e.Channel .. " event!")
--         _D(payload)
--     end)
-- end