Ext.ModEvents.BG3SX.StartSexSpellUsed:Subscribe(function (e)
    _P("[BG3SX][Events] StartSexSpellUsed received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.SexAnimationChange:Subscribe(function (e)
    _P("[BG3SX][Events] SexAnimationChange received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.SceneInit:Subscribe(function (e)
    _P("[BG3SX][Events] SceneInit received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.SceneCreated:Subscribe(function (e)
    _P("[BG3SX][Events] SceneCreated received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.ActorInit:Subscribe(function (e)
    _P("[BG3SX][Events] ActorInit received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.ActorCreated:Subscribe(function (e)
    _P("[BG3SX][Events] ActorCreated received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.AnimationChange:Subscribe(function (e)
    _P("[BG3SX][Events] AnimationChange received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.SoundChange:Subscribe(function (e)
    _P("[BG3SX][Events] SoundChange received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.SceneMove:Subscribe(function (e)
    _P("[BG3SX][Events] SceneMove received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.SceneSwitchPlacesBefore:Subscribe(function (e)
    _P("[BG3SX][Events] SceneSwitchPlacesBefore received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.SceneSwitchPlacesAfter:Subscribe(function (e)
    _P("[BG3SX][Events] SceneSwitchPlacesAfter received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.CameraHeightChange:Subscribe(function (e)
    _P("[BG3SX][Events] CameraHeightChange received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.ActorDressed:Subscribe(function (e)
    _P("[BG3SX][Events] ActorDressed received with PayLoad: ")
    _D(e)
end)
Ext.ModEvents.BG3SX.GenitalChange:Subscribe(function (e)
    _P("[BG3SX][Events] GenitalChange received with PayLoad: ")
    _D(e)
end)
-- Ext.ModEvents.BG3SX.NPCStrip:Subscribe(function (e)
--     _P("[BG3SX][Events] NPCStrip received with PayLoad: ")
--     _D(e)
-- end)
-- Ext.ModEvents.BG3SX.NPCDress:Subscribe(function (e)
--     _P("[BG3SX][Events] NPCDress received with PayLoad: ")
--     _D(e)
-- end)

-- You can also subscribe to all events and filter them out
-- Depending on how many mods will use this and how many events there will be over time, this might get laggy
-- for _,event in pairs(Mods.BG3SX.Data.ModEvents) do
--     Ext.ModEvents.BG3SX[event]:Subscribe(function (e)
--         if event == "ActorDressed" then
--             _P("Recieved " .. event .. " event!")
--             _D(e[1])
--         else
--             _P("Recieved " .. event .. " event!")
--             _D(e[1])
--         end
--     end)
-- end